title: OceanVoyage
description: Premium Cruise Booking Platform
theme: jekyll-theme-cayman

# GitHub Pages settings
baseurl: "/travel3" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Social media
twitter_username: oceanvoyage
github_username: oceanvoyage

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Exclude from processing
exclude:
  - node_modules/
  - .next/
  - src/
  - public/
  - package.json
  - package-lock.json
  - next.config.ts
  - tsconfig.json
  - eslint.config.mjs
  - postcss.config.mjs
  - .gitignore
